#As we know we cant change the tuple but we can convert ito into list and then make changes into it and convert again in tuple
t1=("Nishant","Bharat")
tempList=list(t1)
tempList.pop()
print(t1)
tempList.append("Bharat")
print(tempList)
tempList.append("Sharma")
print(tempList)
t1=tuple(tempList)
print(t1)
t2=(1,1,2,4,5,3,3,2,3)
print(len(t2))
print("Count of 3 : ",t2.count(3))
print("Index of 3 : ",t2.index(2))
print("Index of 3 : ",t2.index(2,0,))#index with three parameters (index of value to search,start,end)
